=== Sergey92S/EpamLab5/xml/bank.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified">
	<xs:element name="banks" type="BanksType" />

	<xs:complexType name="BanksType">
		<xs:sequence>
			<xs:element name="bank" type="BankType"
						minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="BankType">
		<xs:sequence>
			<xs:element name="depositor-bank" type="DepositorBankType"
				minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="DepositorBankType">
		<xs:sequence>
			<xs:element name="depositor" type="DepositorType"
				minOccurs="1" maxOccurs="1" />
			<xs:element name="bank-deposits" type="BankDepositsType"
				minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="BankDepositsType">
		<xs:sequence>
			<xs:element name="bank-deposit" type="BankDepositType"
				minOccurs="1" maxOccurs="10" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="DepositorType">
		<xs:complexContent>
			<xs:extension base="Component">
				<xs:sequence>
					<xs:element name="name" type="NameType" minOccurs="1"
								maxOccurs="1" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="NameType">
		<xs:attribute name="firstname" type="xs:string" default="unknown" use="optional"/>
		<xs:attribute name="surname" type="xs:string" use="required" />
	</xs:complexType>

	<xs:complexType name="BankDepositType">
		<xs:complexContent>
			<xs:extension base="Component">
				<xs:sequence>
					<xs:element name="bankname" type="xs:string" minOccurs="1"
								maxOccurs="1" />
					<xs:element name="country" type="xs:string" minOccurs="1"
								maxOccurs="1" />
					<xs:element name="type" type="type" minOccurs="1"
								maxOccurs="1" />
					<xs:element name="accountid" type="accountid" minOccurs="1"
								maxOccurs="1" />
					<xs:element name="profitability" type="xs:integer"
								minOccurs="1" maxOccurs="1" />
					<xs:element name="timeconstraints" type="xs:integer"
								minOccurs="1" maxOccurs="1" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="Component" abstract="true">
		<xs:attribute name="id" type="xs:ID" use="required" />
	</xs:complexType>

	<xs:simpleType name="type">
		<xs:restriction base="xs:string">
			<xs:enumeration value="poste_restante" />
			<xs:enumeration value="urgent" />
			<xs:enumeration value="metallic" />
			<xs:enumeration value="checking" />
			<xs:enumeration value="savings" />
			<xs:enumeration value="rollup" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="accountid">
		<xs:restriction base="xs:integer">
			<xs:pattern value="[0-9]{6}" />
		</xs:restriction>
	</xs:simpleType>

</xs:schema>

=== Sergey92S/EpamLab5/xml/bank.xml
<?xml version="1.0" encoding="UTF-8"?>
<banks xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="bank.xsd">
	<bank>
		<depositor-bank>
			<depositor id="ID-D1">
				<name firstname="Sergey" surname="Shmouradko" />
			</depositor>
			<bank-deposits>
				<bank-deposit id="ID-B1">
					<bankname>Sberbank</bankname>
					<country>Russia</country>
					<type>poste_restante</type>
					<accountid>111111</accountid>
					<profitability>4</profitability>
					<timeconstraints>1</timeconstraints>
				</bank-deposit>
				<bank-deposit id="ID-B2">
					<bankname>Deutchebank</bankname>
					<country>Germany</country>
					<type>urgent</type>
					<accountid>222222</accountid>
					<profitability>2</profitability>
					<timeconstraints>2</timeconstraints>
				</bank-deposit>
				<bank-deposit id="ID-B3">
					<bankname>Belarusbank</bankname>
					<country>Belarus</country>
					<type>metallic</type>
					<accountid>333333</accountid>
					<profitability>5</profitability>
					<timeconstraints>3</timeconstraints>
				</bank-deposit>
			</bank-deposits>
		</depositor-bank>
	</bank>
	<bank>
		<depositor-bank>
			<depositor id="ID-D2">
				<name firstname="Oleg" surname="Ivanov" />
			</depositor>
			<bank-deposits>
				<bank-deposit id="ID-B4">
					<bankname>Sberbank</bankname>
					<country>Russia</country>
					<type>poste_restante</type>
					<accountid>111111</accountid>
					<profitability>4</profitability>
					<timeconstraints>1</timeconstraints>
				</bank-deposit>
				<bank-deposit id="ID-B5">
					<bankname>Deutchebank</bankname>
					<country>Germany</country>
					<type>urgent</type>
					<accountid>222222</accountid>
					<profitability>2</profitability>
					<timeconstraints>2</timeconstraints>
				</bank-deposit>
				<bank-deposit id="ID-B6">
					<bankname>Belarusbank</bankname>
					<country>Belarus</country>
					<type>metallic</type>
					<accountid>333333</accountid>
					<profitability>5</profitability>
					<timeconstraints>3</timeconstraints>
				</bank-deposit>
			</bank-deposits>
		</depositor-bank>
	</bank>
	<bank>
		<depositor-bank>
			<depositor id="ID-D3">
				<name firstname="Fedor" surname="Fedorov" />
			</depositor>
			<bank-deposits>
				<bank-deposit id="ID-B7">
					<bankname>Sberbank</bankname>
					<country>Russia</country>
					<type>poste_restante</type>
					<accountid>111111</accountid>
					<profitability>4</profitability>
					<timeconstraints>1</timeconstraints>
				</bank-deposit>
				<bank-deposit id="ID-B8">
					<bankname>Deutchebank</bankname>
					<country>Germany</country>
					<type>urgent</type>
					<accountid>222222</accountid>
					<profitability>2</profitability>
					<timeconstraints>2</timeconstraints>
				</bank-deposit>
				<bank-deposit id="ID-B9">
					<bankname>Belarusbank</bankname>
					<country>Belarus</country>
					<type>metallic</type>
					<accountid>333333</accountid>
					<profitability>5</profitability>
					<timeconstraints>3</timeconstraints>
				</bank-deposit>
			</bank-deposits>
		</depositor-bank>
	</bank>
	<bank>
		<depositor-bank>
			<depositor id="ID-D4">
				<name firstname="Fedor" surname="Fedorov" />
			</depositor>
			<bank-deposits>
				<bank-deposit id="ID-B10">
					<bankname>Sberbank</bankname>
					<country>Russia</country>
					<type>poste_restante</type>
					<accountid>111111</accountid>
					<profitability>4</profitability>
					<timeconstraints>1</timeconstraints>
				</bank-deposit>
				<bank-deposit id="ID-B11">
					<bankname>Deutchebank</bankname>
					<country>Germany</country>
					<type>urgent</type>
					<accountid>222222</accountid>
					<profitability>2</profitability>
					<timeconstraints>2</timeconstraints>
				</bank-deposit>
				<bank-deposit id="ID-B12">
					<bankname>Belarusbank</bankname>
					<country>Belarus</country>
					<type>metallic</type>
					<accountid>333333</accountid>
					<profitability>5</profitability>
					<timeconstraints>3</timeconstraints>
				</bank-deposit>
			</bank-deposits>
		</depositor-bank>
	</bank>
	<bank>
		<depositor-bank>
			<depositor id="ID-D5">
				<name firstname="Petr" surname="Petrov" />
			</depositor>
			<bank-deposits>
				<bank-deposit id="ID-B13">
					<bankname>Sberbank</bankname>
					<country>Russia</country>
					<type>poste_restante</type>
					<accountid>111111</accountid>
					<profitability>4</profitability>
					<timeconstraints>1</timeconstraints>
				</bank-deposit>
				<bank-deposit id="ID-B14">
					<bankname>Deutchebank</bankname>
					<country>Germany</country>
					<type>urgent</type>
					<accountid>222222</accountid>
					<profitability>2</profitability>
					<timeconstraints>2</timeconstraints>
				</bank-deposit>
			</bank-deposits>
		</depositor-bank>
	</bank>
	<bank>
		<depositor-bank>
			<depositor id="ID-D6">
				<name firstname="Alex" surname="Alexandrov" />
			</depositor>
			<bank-deposits>
				<bank-deposit id="ID-B15">
					<bankname>Sberbank</bankname>
					<country>Russia</country>
					<type>poste_restante</type>
					<accountid>111111</accountid>
					<profitability>4</profitability>
					<timeconstraints>1</timeconstraints>
				</bank-deposit>
				<bank-deposit id="ID-B16">
					<bankname>Deutchebank</bankname>
					<country>Germany</country>
					<type>urgent</type>
					<accountid>222222</accountid>
					<profitability>2</profitability>
					<timeconstraints>2</timeconstraints>
				</bank-deposit>
			</bank-deposits>
		</depositor-bank>
	</bank>
	<bank>
		<depositor-bank>
			<depositor id="ID-D7">
				<name firstname="John" surname="Johnes" />
			</depositor>
			<bank-deposits>
				<bank-deposit id="ID-B17">
					<bankname>Sberbank</bankname>
					<country>Russia</country>
					<type>poste_restante</type>
					<accountid>111111</accountid>
					<profitability>4</profitability>
					<timeconstraints>1</timeconstraints>
				</bank-deposit>
			</bank-deposits>
		</depositor-bank>
	</bank>
	<bank>
		<depositor-bank>
			<depositor id="ID-D8">
				<name firstname="John" surname="Smith" />
			</depositor>
			<bank-deposits>
				<bank-deposit id="ID-B18">
					<bankname>Sberbank</bankname>
					<country>Russia</country>
					<type>poste_restante</type>
					<accountid>111111</accountid>
					<profitability>4</profitability>
					<timeconstraints>1</timeconstraints>
				</bank-deposit>
			</bank-deposits>
		</depositor-bank>
	</bank>
	<bank>
		<depositor-bank>
			<depositor id="ID-D9">
				<name firstname="George" surname="Bush" />
			</depositor>
			<bank-deposits>
				<bank-deposit id="ID-B19">
					<bankname>Sberbank</bankname>
					<country>Russia</country>
					<type>poste_restante</type>
					<accountid>111111</accountid>
					<profitability>4</profitability>
					<timeconstraints>1</timeconstraints>
				</bank-deposit>
			</bank-deposits>
		</depositor-bank>
	</bank>
	<bank>
		<depositor-bank>
			<depositor id="ID-D10">
				<name firstname="Bill" surname="Clinton" />
			</depositor>
			<bank-deposits>
				<bank-deposit id="ID-B20">
					<bankname>Sberbank</bankname>
					<country>Russia</country>
					<type>poste_restante</type>
					<accountid>111111</accountid>
					<profitability>4</profitability>
					<timeconstraints>1</timeconstraints>
				</bank-deposit>
			</bank-deposits>
		</depositor-bank>
	</bank>
	<bank>
		<depositor-bank>
			<depositor id="ID-D11">
				<name firstname="Hillary" surname="Clinton" />
			</depositor>
			<bank-deposits>
				<bank-deposit id="ID-B21">
					<bankname>Sberbank</bankname>
					<country>Russia</country>
					<type>poste_restante</type>
					<accountid>111111</accountid>
					<profitability>4</profitability>
					<timeconstraints>1</timeconstraints>
				</bank-deposit>
			</bank-deposits>
		</depositor-bank>
	</bank>
	<bank>
		<depositor-bank>
			<depositor id="ID-D12">
				<name firstname="Donald" surname="Trump" />
			</depositor>
			<bank-deposits>
				<bank-deposit id="ID-B22">
					<bankname>Sberbank</bankname>
					<country>Russia</country>
					<type>poste_restante</type>
					<accountid>111111</accountid>
					<profitability>4</profitability>
					<timeconstraints>1</timeconstraints>
				</bank-deposit>
			</bank-deposits>
		</depositor-bank>
	</bank>
	<bank>
		<depositor-bank>
			<depositor id="ID-D13">
				<name firstname="Michael" surname="Jackson" />
			</depositor>
			<bank-deposits>
				<bank-deposit id="ID-B23">
					<bankname>Sberbank</bankname>
					<country>Russia</country>
					<type>poste_restante</type>
					<accountid>111111</accountid>
					<profitability>4</profitability>
					<timeconstraints>1</timeconstraints>
				</bank-deposit>
			</bank-deposits>
		</depositor-bank>
	</bank>
	<bank>
		<depositor-bank>
			<depositor id="ID-D14">
				<name firstname="Mickael" surname="Jordan" />
			</depositor>
			<bank-deposits>
				<bank-deposit id="ID-B24">
					<bankname>Sberbank</bankname>
					<country>Russia</country>
					<type>poste_restante</type>
					<accountid>111111</accountid>
					<profitability>4</profitability>
					<timeconstraints>1</timeconstraints>
				</bank-deposit>
			</bank-deposits>
		</depositor-bank>
	</bank>
	<bank>
		<depositor-bank>
			<depositor id="ID-D15">
				<name firstname="Diego" surname="Maradona" />
			</depositor>
			<bank-deposits>
				<bank-deposit id="ID-B25">
					<bankname>Sberbank</bankname>
					<country>Russia</country>
					<type>poste_restante</type>
					<accountid>111111</accountid>
					<profitability>4</profitability>
					<timeconstraints>1</timeconstraints>
				</bank-deposit>
			</bank-deposits>
		</depositor-bank>
	</bank>
	<bank>
		<depositor-bank>
			<depositor id="ID-D16">
				<name firstname="Zinedine" surname="Zidane" />
			</depositor>
			<bank-deposits>
				<bank-deposit id="ID-B26">
					<bankname>Sberbank</bankname>
					<country>Russia</country>
					<type>poste_restante</type>
					<accountid>111111</accountid>
					<profitability>4</profitability>
					<timeconstraints>1</timeconstraints>
				</bank-deposit>
			</bank-deposits>
		</depositor-bank>
	</bank>
</banks>
